class Config:
	# Grid
	SIZE = 16
	FOREST_PATCHES = 16
	WATER_PATCHES = 16
	FOREST_RENEW_TURNS = 5

	# Rendering
	TILE_SCALE = 32

	# Agent
	NUM_AGENTS = 8
	AGENT_VIEW_RADIUS = 5
	MAX_HEALTH = 10
	MAX_WATER  = 10
	MAX_FOOD   = 10
	ATTACK_DAMAGE = 5
	DRINK_SIZE = 5
	FOOD_SIZE = 5