name: null

channels:
  - intel
  - conda-forge
  - defaults

dependencies:
  # - bokeh
  # - gh
  # - git
  # - holoviews
  # - jupyterlab>=3.0
  # - jupyterlab-git
  # - jupyterlab-lsp
  # - matplotlib
  - pandas
  # - panel
  - pip
  - pip:
    - -r /tmp/requirements.txt
  - python
  # - pyviz_comms
  # - xeus-python